# Generated by Django 4.1.7 on 2023-04-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
