# Generated by Django 4.1.7 on 2023-04-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_response_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
