"""
Django settings for game_forum project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
# from config import CKEDITOR_CONFIGS
from ckeditor.configs import DEFAULT_CONFIG

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-dj7fqxu!)n*5$+6f-))#om31t-xy6&ra(8^ivoqm_cb5v2zpuz'

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'ckeditor',
    'ckeditor_uploader',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'forum',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'game_forum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'game_forum.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = (BASE_DIR / 'static')

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_UPLOAD_PATH = 'media/uploads'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_THUMBNAIL_SIZE = (300, 300)
CKEDITOR_IMAGE_QUALITY = 40
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_ALLOW_NONIMAGE_FILES = True
# CKEDITOR_BASEPATH = "/static/ckeditor/"

CUSTOM_TOOLBAR = [
    {
        'name': 'document',
        'items': [
            'Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', '-',
            'TextColor', 'BGColor', '-',
            'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock',
        ],
    },
    {
        'name': 'widgets',
        'items': [
            'Undo', 'Redo', '-',
            'NumberedList', 'BulletedList', '-',
            'Outdent', 'Indent', '-',
            'Link', 'Unlink', '-',
            'Image', 'CodeSnippet', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', '-'
            'Blockquote', '-',
            'ShowBlocks', 'Maximize',
        ],
    },
]

CKEDITOR_CONFIGS = {
    'default': DEFAULT_CONFIG,
    'my-custom-toolbar': {
        'skin': 'mono-lisa',
        'toolbar': CUSTOM_TOOLBAR,
        'toolbarGroups': None,
        'extraPlugins': ','.join(['image2', 'codesnippet']),
        'removePlugins': ','.join(['image']),
        'codeSnippet_theme': 'xcode',
    },
}

